INSERT INTO locations VALUES (NULL,'Abanilla',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Abarán',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Águilas',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Albudeite',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Alcantarilla',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Aledo',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Alguazas',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Alhama de Murcia',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Archena',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Beniel',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Blanca',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Bullas',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Calasparra',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Campos del Río',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Caravaca de la Cruz',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Cartagena',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Cehegín',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Ceutí',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Cieza',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Fortuna',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Fuente Álamo de Murcia',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Jumilla',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Las Torres de Cotillas',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'La Unión',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Librilla',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Lorca',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Lorquí',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Los Alcázares',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Mazarrón',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Molina de Segura',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Moratalla',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Mula',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Murcia',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Ojós',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Pliego',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Puerto Lumbreras',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Ricote',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'San Javier',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'San Pedro del Pinatar',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Santomera',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Torre-Pacheco',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Totana',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Ulea',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Villanueva del Río Segura',NOW(),NULL);
INSERT INTO locations VALUES (NULL,'Yecla',NOW(),NULL);